# Generated by Django 2.0.7 on 2018-09-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180906_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='city',
            field=models.CharField(max_length=64),
        ),
    ]
