# Generated by Django 2.0.7 on 2018-09-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('duration_of_trip', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=128, null=True)),
                ('residence_address', models.CharField(blank=True, max_length=128, null=True)),
                ('trip_status', models.CharField(blank=True, max_length=128, null=True)),
                ('car_type', models.CharField(blank=True, max_length=64, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_check', to='customer.Customer')),
            ],
        ),
    ]
