# Generated by Django 2.0.7 on 2018-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(blank=True, choices=[('ended', 'Ended'), ('ongoing', 'Ongoing')], max_length=128, null=True),
        ),
    ]
