# Generated by Django 2.0.7 on 2018-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcheck',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
