# Generated by Django 2.0.7 on 2018-09-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_auto_20180913_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destination.Destination'),
        ),
    ]
