# Generated by Django 2.0.7 on 2018-09-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
        ('itinerary', '0003_auto_20180913_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='destination',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.ManyToManyField(blank=True, null=True, to='destination.Destination'),
        ),
    ]
