# Generated by Django 2.0.7 on 2018-09-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_auto_20180913_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='destination',
            field=models.ManyToManyField(blank=True, to='destination.Destination'),
        ),
    ]
