# Generated by Django 2.0.7 on 2018-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_auto_20180913_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
