# Generated by Django 2.0.7 on 2018-09-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0009_itinerary_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
    ]
