# Generated by Django 2.0.7 on 2018-09-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rod', models.BooleanField()),
                ('mattress', models.BooleanField()),
                ('zip', models.BooleanField()),
                ('rain_cover', models.BooleanField()),
                ('ladder', models.BooleanField()),
                ('straps', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tent_check', to='customer.Customer')),
            ],
        ),
    ]
